---
apt_repositories:
  - "deb https://mirror.hetzner.com/ubuntu/packages {{ ansible_distribution_release }} main restricted universe multiverse"
  - "deb https://mirror.hetzner.com/ubuntu/packages {{ ansible_distribution_release }}-updates main restricted universe multiverse"
  - "deb https://mirror.hetzner.com/ubuntu/packages {{ ansible_distribution_release }}-backports main restricted universe multiverse"
  - "deb https://mirror.hetzner.com/ubuntu/packages {{ ansible_distribution_release }}-security main restricted universe multiverse"
apt_packages:
  - man
  - vim
  - inxi
  - dmidecode
  - dnsutils
  - file
  - hddtemp
  - lm-sensors
  - usbutils
  - bash-completion
  - htop
  - git

common_sysctl:
  - name: net.ipv4.conf.default.rp_filter
    value: 1
  - name: net.ipv4.conf.all.rp_filter
    value: 1
  - name: net.ipv4.conf.default.accept_redirects
    value: 0
  - name: net.ipv4.conf.all.accept_redirects
    value: 0
  - name: net.ipv6.conf.default.accept_redirects
    value: 0
  - name: net.ipv6.conf.all.accept_redirects
    value: 0
  - name: net.ipv4.conf.default.secure_redirects
    value: 0
  - name: net.ipv4.conf.all.secure_redirects
    value: 0
  - name: net.ipv4.conf.default.send_redirects
    value: 0
  - name: net.ipv4.conf.all.send_redirects
    value: 0
  - name: net.ipv4.conf.default.accept_source_route
    value: 0
  - name: net.ipv4.conf.all.accept_source_route
    value: 0

users_accounts:
  - name: ajames
    groups:
      - sudo
      - docker
    shell: /bin/bash
    authorized_keys:
      - file: ajames.pub
  - name: zas
    groups:
      - sudo
      - docker
    shell: /bin/bash
    authorized_keys:
      - file: zas.pub
