---
apt_repositories:
  - "deb https://mirror.hetzner.com/ubuntu/packages {{ ansible_distribution_release }} main restricted universe multiverse"
  - "deb https://mirror.hetzner.com/ubuntu/packages {{ ansible_distribution_release }}-updates main restricted universe multiverse"
  - "deb https://mirror.hetzner.com/ubuntu/packages {{ ansible_distribution_release }}-backports main restricted universe multiverse"
  - "deb https://mirror.hetzner.com/ubuntu/packages {{ ansible_distribution_release }}-security main restricted universe multiverse"
apt_packages:
  - man
  - vim
  - inxi
  - dmidecode
  - dnsutils
  - file
  - hddtemp
  - lm-sensors
  - usbutils
  - bash-completion
  - htop
  - git

users_accounts:
  - name: ajames
    groups:
      - sudo
      - docker
    shell: /bin/bash
    authorized_keys:
      - file: ajames.pub
  - name: zas
    groups:
      - sudo
      - docker
    shell: /bin/bash
    authorized_keys:
      - file: zas.pub
